--liquibase formatted sql

--changeset tsykanov:init-table-User splitStatements:false runOnChange:true runInTransaction:true failOnError:true
CREATE TABLE IF NOT EXISTS "User" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ExternalId" character varying(128) NOT NULL,
    "Name" character varying(512) NOT NULL,
    "AvatarUrl" character varying(4096) NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);
--rollback DROP TABLE IF EXISTS "User";

--changeset tsykanov:init-table-Group splitStatements:false runOnChange:true runInTransaction:true failOnError:true
CREATE TABLE IF NOT EXISTS "Group" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ExternalId" uuid NOT NULL,
    "Name" character varying(4096) NOT NULL,
    "RepetitionProgress" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_Group" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Group_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);
--rollback DROP TABLE IF EXISTS "Group";

--changeset tsykanov:init-table-Sentence splitStatements:false runOnChange:true runInTransaction:true failOnError:true
CREATE TABLE IF NOT EXISTS "Sentence" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ExternalId" uuid NOT NULL,
    "Value" character varying(8192) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_Sentence" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sentence_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);
--rollback DROP TABLE IF EXISTS "Sentence";

--changeset tsykanov:init-table-Word splitStatements:false runOnChange:true runInTransaction:true failOnError:true
CREATE TABLE IF NOT EXISTS "Word" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ExternalId" uuid NOT NULL,
    "Value" character varying(512) NOT NULL,
    "RepetitionProgress" integer NOT NULL,
    "Description" character varying(8192) NULL,
    "ImageUrl" character varying(4096) NULL,
    "GroupId" bigint NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_Word" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Word_Group_GroupId" FOREIGN KEY ("GroupId") REFERENCES "Group" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Word_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);
--rollback DROP TABLE IF EXISTS "Word";

--changeset tsykanov:init-table-SentenceWord splitStatements:false runOnChange:true runInTransaction:true failOnError:true
CREATE TABLE IF NOT EXISTS "SentenceWord" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SentenceId" bigint NOT NULL,
    "WordId" bigint NOT NULL,
    "OrderedNumber" integer NOT NULL,
    CONSTRAINT "PK_SentenceWord" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SentenceWord_Sentence_SentenceId" FOREIGN KEY ("SentenceId") REFERENCES "Sentence" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SentenceWord_Word_WordId" FOREIGN KEY ("WordId") REFERENCES "Word" ("Id") ON DELETE CASCADE
);
--rollback DROP TABLE IF EXISTS "SentenceWord";



